#!/usr/bin/env python3
# Copyright 2025-2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""LAPTOP app: ZED Mini -> LCM point cloud -> Rerun click viewer. NO robot needed.

Stage 1 of swapping the click-to-IK camera from the head D435i to a ZED:
verify the ZED point cloud renders (RGB-colored, clickable) in the same
Rerun viewer the IK apps use, BEFORE wiring it to IkReachBridge/G1.

This is the ZED sibling of ``dimos/robot/unitree/g1/blueprints/perceptive/
unitree_g1_ik_camera.py`` (the Jetson-side D435i publisher), with two deltas:
- the ZED plugs directly into the LAPTOP (no Jetson relay), so the camera
  and the viewer run in ONE blueprint/process;
- ``vis_module("rerun")`` is included here (the D435i node runs headless and
  relies on the laptop app's viewer).

The LCM topic names are the click-to-IK contract shared by unitree-g1-ik-reach /
unitree-g1-okra-harvest / unitree-g1-okra-ik-only-grasp (RerunBridge renders any
LCM channel at entity ``world/<topic>``; IkReachBridge pins clicks to
``/world/camera/pointcloud``):
    ZEDCamera.pointcloud  -> /camera/pointcloud  -> world/camera/pointcloud
    ZEDCamera.color_image -> /camera/color_image -> world/camera/color_image
    ZEDCamera.camera_info -> /camera/camera_info -> world/camera/camera_info

NOTE on frames: the cloud is generated by ``PointCloud2.from_rgbd`` in the
CAMERA COLOR-OPTICAL frame, same as the D435i publisher — so a click's x/y/z
is optical-frame, matching IkReachBridge's expectation. But IkReachBridge's
static torso<-optical SE3 (ik_reach_bridge.py:76-94) is the HEAD D435i mount;
a ZED mounted anywhere else needs its own calibrated transform before any
numerically-correct reach. This stage-1 viewer does not touch that.

Run:
    dimos run unitree-g1-zed-ik-view
    # then: dimos-viewer --connect rerun+http://127.0.0.1:9877/proxy \
    #                    --ws-url ws://127.0.0.1:3030/ws
Requires: pyzed (SDK-matched wheel) + a USB3-connected ZED; lo multicast ON
(sudo ip link set lo multicast on) for in-process LCM, same as the IK apps.
"""

from __future__ import annotations

import os

from dimos.core.coordination.blueprints import autoconnect
from dimos.core.transport import LCMTransport
from dimos.hardware.sensors.camera.zed.camera import ZEDCamera
from dimos.msgs.sensor_msgs.CameraInfo import CameraInfo
from dimos.msgs.sensor_msgs.Image import Image
from dimos.msgs.sensor_msgs.PointCloud2 import PointCloud2
from dimos.visualization.vis_module import vis_module

# ZED unit selection: serial pins a specific camera (multi-camera safe); empty
# falls back to camera_id 0 (the only attached unit). SN17243330 = the ZED Mini
# verified on this laptop 2026-07-16.
_ZED_SERIAL = os.getenv("ZED_SERIAL", "").strip() or None

# Conservative cloud rate, same rationale as the D435i node (one-shot human-click
# pipeline; low rate keeps LCM fragmentation/bandwidth down).
_PC_FPS = float(os.getenv("ZED_PC_FPS", "3.0"))

# NEURAL verified working on this laptop (2026-07-16 smoke test). Downgrade to
# PERFORMANCE if the GPU is busy (e.g. ACT inference sharing the laptop).
_DEPTH_MODE = os.getenv("ZED_DEPTH_MODE", "NEURAL")

_CAM_FPS = int(os.getenv("ZED_FPS", "15"))

# Cloud density: same tuning the D435i pipeline converged on (2mm voxel + 0.8m
# depth truncation, ik_camera_standalone.py) — see unitree_g1_okra_ik_only_grasp_zed.py.
_PC_VOXEL = float(os.getenv("ZED_PC_VOXEL", "0.002"))
_DEPTH_TRUNC = float(os.getenv("ZED_DEPTH_TRUNC", "0.8"))


def _camera_info_overlay(ci):  # type: ignore[no-untyped-def]
    """RerunBridge visual_override: log the camera Pinhole at the COLOR IMAGE
    entity so the RGB frame renders co-located with the cloud (one Spatial3D
    view). Module-level (not a lambda) so the blueprint config stays picklable
    for the forkserver worker. Duplicated from unitree_g1_okra_ik_only_grasp.py
    (a private, non-exported helper) — same established duplication as between
    that file and unitree_g1_okra_harvest.py."""
    return ci.to_rerun(image_topic="world/camera/color_image")


def _pointcloud_rgb_overlay(pc):  # type: ignore[no-untyped-def]
    """RerunBridge visual_override: render the cloud with its TRUE per-point
    camera RGB (so the target shows in real color, easy to click) instead of
    the default height colormap. Falls back to default if a cloud arrives
    without colors. Duplicated from unitree_g1_okra_ik_only_grasp.py for the
    same reason as _camera_info_overlay above."""
    import os as _os

    import numpy as np
    import rerun as rr

    points, colors = pc.as_numpy()
    if colors is None or len(points) == 0:
        return pc.to_rerun()
    rgb = (np.asarray(colors) * 255.0).clip(0, 255).astype(np.uint8)
    radius = float(_os.getenv("IK_PC_POINT_RADIUS", "0.0015"))
    return rr.Points3D(positions=np.asarray(points), colors=rgb, radii=radius)


unitree_g1_zed_ik_view = autoconnect(
    vis_module(
        "rerun",
        rerun_config={
            "visual_override": {
                "world/camera/camera_info": _camera_info_overlay,
                "world/camera/pointcloud": _pointcloud_rgb_overlay,
            },
        },
    ),
    ZEDCamera.blueprint(
        serial_number=_ZED_SERIAL,
        fps=_CAM_FPS,
        enable_depth=True,
        enable_pointcloud=True,
        align_depth_to_color=True,
        pointcloud_fps=_PC_FPS,
        pointcloud_voxel=_PC_VOXEL,
        pointcloud_depth_trunc=_DEPTH_TRUNC,
        camera_info_fps=1.0,
        depth_mode=_DEPTH_MODE,
        # Handheld/bench camera for this viewer: no positional tracking (it wants
        # motion+texture and adds a world-frame TF this stage doesn't use).
        enable_tracking=False,
    ),
).transports(
    {
        ("pointcloud", PointCloud2): LCMTransport("/camera/pointcloud", PointCloud2),
        ("color_image", Image): LCMTransport("/camera/color_image", Image),
        ("camera_info", CameraInfo): LCMTransport("/camera/camera_info", CameraInfo),
    }
)

__all__ = ["unitree_g1_zed_ik_view"]
