# Copyright 2025-2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is auto-generated. Do not edit manually.
# Run `pytest dimos/robot/test_all_blueprints_generation.py` to regenerate.

all_blueprints = {
    "demo-agent": "dimos.agents.demo_agent:demo_agent",
    "demo-agent-camera": "dimos.agents.demo_agent:demo_agent_camera",
    "demo-camera": "dimos.hardware.sensors.camera.module:demo_camera",
    "demo-error-on-name-conflicts": "dimos.robot.unitree.demo_error_on_name_conflicts:demo_error_on_name_conflicts",
    "demo-google-maps-skill": "dimos.agents.skills.demo_google_maps_skill:demo_google_maps_skill",
    "demo-gps-nav": "dimos.agents.skills.demo_gps_nav:demo_gps_nav",
    "demo-grasping": "dimos.manipulation.grasping.demo_grasping:demo_grasping",
    "demo-mcp-stress-test": "dimos.core.tests.stress_test_blueprint:demo_mcp_stress_test",
    "demo-object-scene-registration": "dimos.perception.demo_object_scene_registration:demo_object_scene_registration",
    "demo-osm": "dimos.mapping.osm.demo_osm:demo_osm",
    "demo-skill": "dimos.agents.skills.demo_skill:demo_skill",
    "desk-marker-tf": "dimos.perception.fiducial.blueprints.desk_marker_tf:desk_marker_tf",
    "mid360": "dimos.hardware.sensors.lidar.livox.livox_blueprints:mid360",
    "mid360-fastlio": "dimos.hardware.sensors.lidar.fastlio2.fastlio_blueprints:mid360_fastlio",
    "mid360-fastlio-ray-trace": "dimos.hardware.sensors.lidar.fastlio2.fastlio_blueprints:mid360_fastlio_ray_trace",
    "mid360-fastlio-voxels": "dimos.hardware.sensors.lidar.fastlio2.fastlio_blueprints:mid360_fastlio_voxels",
    "mid360-fastlio-voxels-native": "dimos.hardware.sensors.lidar.fastlio2.fastlio_blueprints:mid360_fastlio_voxels_native",
    "teleop-phone": "dimos.teleop.phone.blueprints:teleop_phone",
    "uintree-g1-primitive-no-nav": "dimos.robot.unitree.g1.blueprints.primitive.uintree_g1_primitive_no_nav:uintree_g1_primitive_no_nav",
    "unitree-g1": "dimos.robot.unitree.g1.blueprints.perceptive.unitree_g1:unitree_g1",
    "unitree-g1-act-arm": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_act_arm:unitree_g1_act_arm",
    "unitree-g1-act-arm-tree": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_act_arm_tree:unitree_g1_act_arm_tree",
    "unitree-g1-act-dryrun": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_act_dryrun:unitree_g1_act_dryrun",
    "unitree-g1-agentic": "dimos.robot.unitree.g1.blueprints.agentic.unitree_g1_agentic:unitree_g1_agentic",
    "unitree-g1-agentic-sim": "dimos.robot.unitree.g1.blueprints.agentic.unitree_g1_agentic_sim:unitree_g1_agentic_sim",
    "unitree-g1-arm-hold": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_arm_hold:unitree_g1_arm_hold",
    "unitree-g1-basic": "dimos.robot.unitree.g1.blueprints.basic.unitree_g1_basic:unitree_g1_basic",
    "unitree-g1-basic-sim": "dimos.robot.unitree.g1.blueprints.basic.unitree_g1_basic_sim:unitree_g1_basic_sim",
    "unitree-g1-coordinator": "dimos.robot.unitree.g1.blueprints.basic.unitree_g1_coordinator:unitree_g1_coordinator",
    "unitree-g1-detection": "dimos.robot.unitree.g1.blueprints.perceptive.unitree_g1_detection:unitree_g1_detection",
    "unitree-g1-full": "dimos.robot.unitree.g1.blueprints.agentic.unitree_g1_full:unitree_g1_full",
    "unitree-g1-gravity-hold-test": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_gravity_hold_test:unitree_g1_gravity_hold_test",
    "unitree-g1-ik-camera": "dimos.robot.unitree.g1.blueprints.perceptive.unitree_g1_ik_camera:unitree_g1_ik_camera",
    "unitree-g1-ik-reach": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_ik_reach:unitree_g1_ik_reach",
    "unitree-g1-joystick": "dimos.robot.unitree.g1.blueprints.basic.unitree_g1_joystick:unitree_g1_joystick",
    "unitree-g1-left-elbow-nudge": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_left_elbow_nudge:unitree_g1_left_elbow_nudge",
    "unitree-g1-left-shoulder-gravity-nudge": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_left_shoulder_gravity_nudge:unitree_g1_left_shoulder_gravity_nudge",
    "unitree-g1-left-shoulder-gravity-probe": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_left_shoulder_gravity_probe:unitree_g1_left_shoulder_gravity_probe",
    "unitree-g1-left-shoulder-gravity25-nudge": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_left_shoulder_gravity25_nudge:unitree_g1_left_shoulder_gravity25_nudge",
    "unitree-g1-left-shoulder-pitch-kp160-nudge": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_left_shoulder_pitch_kp160_nudge:unitree_g1_left_shoulder_pitch_kp160_nudge",
    "unitree-g1-left-shoulder-pitch-nudge": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_left_shoulder_pitch_nudge:unitree_g1_left_shoulder_pitch_nudge",
    "unitree-g1-mid360-fastlio": "dimos.robot.unitree.g1.blueprints.navigation.unitree_g1_mid360_fastlio:unitree_g1_mid360_fastlio",
    "unitree-g1-nav-dual-cam": "dimos.robot.unitree.g1.blueprints.navigation.unitree_g1_nav_dual_cam:unitree_g1_nav_dual_cam",
    "unitree-g1-nav-laptop": "dimos.robot.unitree.g1.blueprints.navigation.unitree_g1_nav_laptop:unitree_g1_nav_laptop",
    "unitree-g1-nav-laptop-cam": "dimos.robot.unitree.g1.blueprints.navigation.unitree_g1_nav_laptop_cam:unitree_g1_nav_laptop_cam",
    "unitree-g1-nav-onboard": "dimos.robot.unitree.g1.blueprints.navigation.unitree_g1_nav_onboard:unitree_g1_nav_onboard",
    "unitree-g1-nav-sim": "dimos.robot.unitree.g1.blueprints.navigation.unitree_g1_nav_sim:unitree_g1_nav_sim",
    "unitree-g1-okra-collect": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_okra_collect:unitree_g1_okra_collect",
    "unitree-g1-okra-harvest": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_okra_harvest:unitree_g1_okra_harvest",
    "unitree-g1-okra-harvest-full": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_okra_harvest_full:unitree_g1_okra_harvest_full",
    "unitree-g1-okra-harvest-ik": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_okra_harvest_ik:unitree_g1_okra_harvest_ik",
    "unitree-g1-okra-harvest-langgraph": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_okra_harvest_langgraph:unitree_g1_okra_harvest_langgraph",
    "unitree-g1-okra-harvest-live": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_okra_harvest_live:unitree_g1_okra_harvest_live",
    "unitree-g1-okra-harvest-live-arm": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_okra_harvest_live_arm:unitree_g1_okra_harvest_live_arm",
    "unitree-g1-okra-harvest-walk": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_okra_harvest_walk:unitree_g1_okra_harvest_walk",
    "unitree-g1-okra-harvest-zed": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_okra_harvest_zed:unitree_g1_okra_harvest_zed",
    "unitree-g1-okra-ik-diffusion": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_okra_ik_diffusion:unitree_g1_okra_ik_diffusion",
    "unitree-g1-okra-ik-only-grasp": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_okra_ik_only_grasp:unitree_g1_okra_ik_only_grasp",
    "unitree-g1-okra-ik-only-grasp-zed": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_okra_ik_only_grasp_zed:unitree_g1_okra_ik_only_grasp_zed",
    "unitree-g1-shm": "dimos.robot.unitree.g1.blueprints.perceptive.unitree_g1_shm:unitree_g1_shm",
    "unitree-g1-sim": "dimos.robot.unitree.g1.blueprints.perceptive.unitree_g1_sim:unitree_g1_sim",
    "unitree-g1-single-joint-nudge": "dimos.robot.unitree.g1.blueprints.manipulation.unitree_g1_single_joint_nudge:unitree_g1_single_joint_nudge",
    "unitree-g1-zed-ik-view": "dimos.robot.unitree.g1.blueprints.perceptive.unitree_g1_zed_ik_view:unitree_g1_zed_ik_view",
    "unity-sim": "dimos.simulation.unity.blueprint:unity_sim",
}


all_modules = {
    "act-bridge": "dimos.robot.unitree.g1.act.act_bridge.ActBridge",
    "b-box-navigation-module": "dimos.navigation.bbox_navigation.BBoxNavigationModule",
    "camera-module": "dimos.hardware.sensors.camera.module.CameraModule",
    "cartesian-motion-controller": "dimos.manipulation.control.servo_control.cartesian_motion_controller.CartesianMotionController",
    "control-coordinator": "dimos.control.coordinator.ControlCoordinator",
    "cost-mapper": "dimos.mapping.costmapper.CostMapper",
    "demo-calculator-skill": "dimos.agents.skills.demo_calculator_skill.DemoCalculatorSkill",
    "demo-robot": "dimos.agents.skills.demo_robot.DemoRobot",
    "desk-static-tf-module": "dimos.perception.fiducial.blueprints.desk_marker_tf.DeskStaticTfModule",
    "detection2-d-module": "dimos.perception.detection.module2D.Detection2DModule",
    "detection3-d-module": "dimos.perception.detection.module3D.Detection3DModule",
    "embedding-memory": "dimos.memory.embedding.EmbeddingMemory",
    "emitter-module": "dimos.utils.demo_image_encoding.EmitterModule",
    "far-planner": "dimos.navigation.nav_stack.modules.far_planner.far_planner.FarPlanner",
    "fast-lio2": "dimos.hardware.sensors.lidar.fastlio2.module.FastLio2",
    "g1-arm-sdk-connection": "dimos.robot.unitree.g1.act.g1_arm_sdk_connection.G1ArmSdkConnection",
    "g1-connection": "dimos.robot.unitree.g1.connection.G1Connection",
    "g1-connection-base": "dimos.robot.unitree.g1.connection.G1ConnectionBase",
    "g1-fast-lio-odometry-bridge": "dimos.robot.unitree.g1.odometry_bridge.G1FastLioOdometryBridge",
    "g1-gripper-connection": "dimos.robot.unitree.g1.act.g1_gripper_connection.G1GripperConnection",
    "g1-high-level-dds-sdk": "dimos.robot.unitree.g1.effectors.high_level.dds_sdk.G1HighLevelDdsSdk",
    "g1-high-level-web-rtc": "dimos.robot.unitree.g1.effectors.high_level.webrtc.G1HighLevelWebRtc",
    "g1-sim-connection": "dimos.robot.unitree.g1.mujoco_sim.G1SimConnection",
    "g1-single-joint-nudge": "dimos.robot.unitree.g1.act.g1_single_joint_nudge.G1SingleJointNudge",
    "g1-whole-body-connection": "dimos.robot.unitree.g1.wholebody_connection.G1WholeBodyConnection",
    "google-maps-skill-container": "dimos.agents.skills.google_maps_skill_container.GoogleMapsSkillContainer",
    "gps-nav-skill-container": "dimos.agents.skills.gps_nav_skill.GpsNavSkillContainer",
    "grasp-gen-module": "dimos.manipulation.grasping.graspgen_module.GraspGenModule",
    "grasping-module": "dimos.manipulation.grasping.grasping.GraspingModule",
    "gripper-grasp-on-reach": "dimos.robot.unitree.g1.blueprints.manipulation.gripper_grasp_on_reach.GripperGraspOnReach",
    "gstreamer-camera-module": "dimos.hardware.sensors.camera.gstreamer.gstreamer_camera.GstreamerCameraModule",
    "harvest-module": "dimos.robot.unitree.g1.harvest.harvest_module.HarvestModule",
    "ik-reach-bridge": "dimos.robot.unitree.g1.act.ik_reach_bridge.IkReachBridge",
    "joint-trajectory-controller": "dimos.manipulation.control.trajectory_controller.joint_trajectory_controller.JointTrajectoryController",
    "keyboard-teleop": "dimos.robot.unitree.keyboard_teleop.KeyboardTeleop",
    "keyboard-teleop-module": "dimos.teleop.keyboard.keyboard_teleop_module.KeyboardTeleopModule",
    "local-planner": "dimos.navigation.nav_stack.modules.local_planner.local_planner.LocalPlanner",
    "manipulation-module": "dimos.manipulation.manipulation_module.ManipulationModule",
    "map": "dimos.robot.unitree.type.map.Map",
    "marker-tf-module": "dimos.perception.fiducial.marker_tf_module.MarkerTfModule",
    "mcp-client": "dimos.agents.mcp.mcp_client.McpClient",
    "mcp-server": "dimos.agents.mcp.mcp_server.McpServer",
    "memory-module": "dimos.memory2.module.MemoryModule",
    "module-a": "dimos.robot.unitree.demo_error_on_name_conflicts.ModuleA",
    "module-b": "dimos.robot.unitree.demo_error_on_name_conflicts.ModuleB",
    "movement-manager": "dimos.navigation.movement_manager.movement_manager.MovementManager",
    "mujoco-sim-module": "dimos.simulation.engines.mujoco_sim_module.MujocoSimModule",
    "nav-record": "dimos.navigation.nav_stack.modules.nav_record.nav_record.NavRecord",
    "navigation-skill-container": "dimos.agents.skills.navigation.NavigationSkillContainer",
    "object-db-module": "dimos.perception.detection.moduleDB.ObjectDBModule",
    "object-scene-registration-module": "dimos.perception.object_scene_registration.ObjectSceneRegistrationModule",
    "object-tracker2-d": "dimos.perception.object_tracker_2d.ObjectTracker2D",
    "object-tracker3-d": "dimos.perception.object_tracker_3d.ObjectTracker3D",
    "object-tracking": "dimos.perception.object_tracker.ObjectTracking",
    "osm-skill": "dimos.agents.skills.osm.OsmSkill",
    "path-follower": "dimos.navigation.nav_stack.modules.path_follower.path_follower.PathFollower",
    "patrolling-module": "dimos.navigation.patrolling.module.PatrollingModule",
    "perceive-loop-skill": "dimos.perception.perceive_loop_skill.PerceiveLoopSkill",
    "person-follow-skill-container": "dimos.agents.skills.person_follow.PersonFollowSkillContainer",
    "person-tracker": "dimos.perception.detection.person_tracker.PersonTracker",
    "pgo": "dimos.navigation.nav_stack.modules.pgo.pgo.PGO",
    "phone-teleop-module": "dimos.teleop.phone.phone_teleop_module.PhoneTeleopModule",
    "pick-and-place-module": "dimos.manipulation.pick_and_place_module.PickAndPlaceModule",
    "ray-tracing-voxel-map": "dimos.mapping.ray_tracing.module.RayTracingVoxelMap",
    "real-sense-camera": "dimos.hardware.sensors.camera.realsense.camera.RealSenseCamera",
    "receiver-module": "dimos.utils.demo_image_encoding.ReceiverModule",
    "recorder": "dimos.memory2.module.Recorder",
    "reid-module": "dimos.perception.detection.reid.module.ReidModule",
    "relocalization-module": "dimos.mapping.relocalization.module.RelocalizationModule",
    "replanning-a-star-planner": "dimos.navigation.replanning_a_star.module.ReplanningAStarPlanner",
    "rerun-bridge-module": "dimos.visualization.rerun.bridge.RerunBridgeModule",
    "rerun-web-socket-server": "dimos.visualization.rerun.websocket_server.RerunWebSocketServer",
    "right-wrist-teleimager-camera": "dimos.robot.unitree.g1.camera.teleimager_camera_module.RightWristTeleimagerCamera",
    "security-module": "dimos.experimental.security_demo.security_module.SecurityModule",
    "semantic-search": "dimos.memory2.module.SemanticSearch",
    "simple-phone-teleop": "dimos.teleop.phone.phone_extensions.SimplePhoneTeleop",
    "simple-planner": "dimos.navigation.nav_stack.modules.simple_planner.simple_planner.SimplePlanner",
    "spatial-memory": "dimos.perception.spatial_perception.SpatialMemory",
    "speak-skill": "dimos.agents.skills.speak_skill.SpeakSkill",
    "tare-planner": "dimos.navigation.nav_stack.modules.tare_planner.tare_planner.TarePlanner",
    "teleimager-camera": "dimos.robot.unitree.g1.camera.teleimager_camera_module.TeleimagerCamera",
    "temporal-memory": "dimos.perception.experimental.temporal_memory.temporal_memory.TemporalMemory",
    "terrain-analysis": "dimos.navigation.nav_stack.modules.terrain_analysis.terrain_analysis.TerrainAnalysis",
    "terrain-map-ext": "dimos.navigation.nav_stack.modules.terrain_map_ext.terrain_map_ext.TerrainMapExt",
    "umi-diffusion-bridge": "dimos.robot.unitree.g1.act.umi_diffusion_bridge.UmiDiffusionBridge",
    "unitree-g1-skill-container": "dimos.robot.unitree.g1.skill_container.UnitreeG1SkillContainer",
    "unity-bridge-module": "dimos.simulation.unity.module.UnityBridgeModule",
    "vlm-agent": "dimos.agents.vlm_agent.VLMAgent",
    "vlm-stream-tester": "dimos.agents.vlm_stream_tester.VlmStreamTester",
    "voxel-grid-mapper": "dimos.mapping.voxels.VoxelGridMapper",
    "wavefront-frontier-explorer": "dimos.navigation.frontier_exploration.wavefront_frontier_goal_selector.WavefrontFrontierExplorer",
    "web-input": "dimos.agents.web_human_input.WebInput",
    "websocket-vis-module": "dimos.web.websocket_vis.websocket_vis_module.WebsocketVisModule",
    "zed-camera": "dimos.hardware.sensors.camera.zed.camera.ZEDCamera",
    "zmq-camera": "dimos.robot.unitree.g1.camera.zmq_camera_module.ZmqCamera",
}
